server:
  port: 8081

spring:
  jpa:
    # 让hibernate打印执行的sql
    show-sql: true
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-provider-user

logging:
  level:
    root: info
    # 配置日志级别，让hibernate打印出执行的sql参数
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defalutZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server上
    prefer-ip-address: true
