server:
  port: 8080

spring:
  jpa:
    show-sql: true

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.tye.descriptor.sql.BasicBinder: trace
    org.hibernate.tye.descriptor.sql.BasicExtrator: trace
