server:
  port: 8010

spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie-ribbon-config-globa

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/不能少
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  instance:
    # 是否注册ip到eureka server，如不指定或者设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

# 默认情况下Ribbon是懒加载的---首次请求Ribbon相关类才会初始化，会导致首次请求过慢，可以配置饥饿加载
ribbon:
  eager-load:
    enabled: true
    #多个用,分隔
    clients: microservice-provider-user