server:
  port: 8010

spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie-ribbon-config-java

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/不能少
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  instance:
    # 是否注册ip到eureka server，如不指定
    prefer-ip-address: true
